services:
  app:
    image: ghcr.io/hargata/lubelogger:latest
    restart: unless-stopped
    # volumes used to keep data persistent
    volumes:
      - /volume1/docker/lubelogger/data:/App/data
      - /volume1/docker/lubelogger/keys:/root/.aspnet/DataProtection-Keys
    # expose port and/or use serving via traefik
    ports:
      - 8080:8080

volumes:
  data:
  keys:
